openapi: 3.0.3
info:
  title: Vehicle Management API
  version: 1.0.0
servers:
  - url: http://localhost:8080
tags:
  - name: Vehicle Management

paths:
  /vehicles/abstraction:
    get:
      operationId: queryVehicles
      tags:
        - Vehicle Management
      summary: Retrieve vehicle information
      parameters:
        - in: query
          name: type
          schema:
            $ref: "#/components/schemas/VehicleType"
          description: The type of the vehicle to be filtered
        - in: query
          name: color
          schema:
            $ref: "#/components/schemas/VehicleColor"
          description: The color of the vehicle to be filtered
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Vehicle"

components:
  schemas:
    #---------------------------------------------------------------------------
    # Enum utilities
    #---------------------------------------------------------------------------
    VehicleType:
      type: string
      enum: ["CAR", "TRUCK"]
    VehicleColor:
      type: string
      enum: ["RED", "GREEN", "BLUE"]
    #---------------------------------------------------------------------------
    # Model objects
    #---------------------------------------------------------------------------
    Vehicle:
      type: object
      required:
        - vehicleType
      properties:
        vehicleType:
          type: string
          description: "possible values are described in enum VehicleType"
        color:
          type: string
          description: "possible values are described in enum VehicleColor"
        data:
          $ref: "#/components/schemas/VehicleData"
    #---------------------------------------------------------------------------
    # Abstract class with discriminator 'vehicleType'
    #---------------------------------------------------------------------------
    VehicleData:
      type: object
      required:
        - vehicleType
      properties:
        vehicleType:
          type: string
      discriminator:
        propertyName: vehicleType
        mapping:
          "CAR": "#/components/schemas/CarData"
          "TRUCK": "#/components/schemas/TruckData"
    #---------------------------------------------------------------------------
    # Concrete classes
    #---------------------------------------------------------------------------
    CarData:
      allOf:
        - $ref: "#/components/schemas/VehicleData"
        - type: object
          properties:
            carAttributes:
              type: string
    TruckData:
      allOf:
        - $ref: "#/components/schemas/VehicleData"
        - type: object
          properties:
            truckAttributes:
              type: string
            truckCountWheels:
              type: integer
